### ISSUE TITLE
Django - simple file upload 

### ISSUE THREAD

**Issue by igchoi** [choilab/BTN707-2021-Fall#4]
Django [example](https://docs.djangoproject.com/en/4.1/topics/http/file-uploads/) - check this.

**Comment by igchoi** [comment]
먼저 장고웹서버가 어떻게 작동하는지 이해하고 따라해 보세요.
1. 웹서버 - 프로젝트(e.g. mysite) [tutorial](https://docs.djangoproject.com/ko/4.1/intro/tutorial01/)
2. 웹앱 - 앱(e.g. polls)
3. then, check [simple korean example](https://domdom.tistory.com/entry/django-%EC%9E%A5%EA%B3%A0%EC%97%90%EC%84%9C-%EC%82%AC%EC%9A%A9%EC%9E%90%EA%B0%80-%EC%97%85%EB%A1%9C%EB%93%9C%ED%95%9C-%ED%8C%8C%EC%9D%BC-%EC%A0%80%EC%9E%A5%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)

**Comment by choilab** [comment]
@limchanyoung1116 check this repository - this is very naive but 'workable' WebApp - FoldSearch..  https://github.com/igchoi/foldsearch
